name: Build & Release

on:
  push:
    branches: [ main ]      # 每次 push 自动生成 nightly
  workflow_dispatch:        # 手动触发
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        include:
          - os: windows-latest
            triplet: x64-windows
            exe: main.exe
          - os: ubuntu-latest
            triplet: x64-linux
            exe: main
          - os: macos-latest
            triplet: x64-osx
            exe: main

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Convert to full clone
        run: git fetch --unshallow
      - name: Checkout vcpkg（完整官方库）
        run: |
          git clone --depth 1 https://github.com/Microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.bat        # Win
          # mac/linux 用 ./vcpkg/bootstrap-vcpkg.sh

      - name: Install dependencies
        run: |
          ./vcpkg/vcpkg install sfml:x64-windows --triplet=x64-windows

      - name: Configure & Build
        run: |
          cmake -B build -S . -DCMAKE_TOOLCHAIN_FILE=./vcpkg/scripts/buildsystems/vcpkg.cmake
          cmake --build build --config Release
          
      - name: Package
        shell: bash
        run: |
          mkdir -p package
          cp build/bin/Release/${{ matrix.exe }} package/
          cp -r vcpkg/installed/${{ matrix.triplet }}/bin/*.dll package/ 2>/dev/null || true   # Win
          cp -r vcpkg/installed/${{ matrix.triplet }}/lib/*.dylib package/ 2>/dev/null || true # macOS
          (cd package && zip -r ../PongDemo-${{ matrix.triplet }}.zip .)

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        if: github.event_name != 'pull_request'
        with:
          tag_name: nightly
          name: "Nightly Build"
          body: "Auto-generated nightly build for ${{ matrix.triplet }}"
          files: PongDemo-${{ matrix.triplet }}.zip
          draft: false
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}